const DATABASE_RESET_CONFIRMATION = '초기화';
const DATABASE_RESET_SUCCESS_MESSAGE = '해당 아카데미 데이터가 초기화되었습니다.';
const DATABASE_RESET_CONFIRMATION_MESSAGE = '확인을 위해 "초기화"를 입력해주세요.';
const DATABASE_RESET_FAILURE_MESSAGE = '데이터를 초기화하지 못했습니다. 기존 데이터는 그대로 유지됩니다.';

module.exports = {
    DATABASE_RESET_CONFIRMATION,
    DATABASE_RESET_SUCCESS_MESSAGE,
    DATABASE_RESET_CONFIRMATION_MESSAGE,
    DATABASE_RESET_FAILURE_MESSAGE,
};
