export const consultationDetailPdfStyles = {
  container: {
    width: '595px',
    padding: '28px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    boxSizing: 'border-box' as const,
  },
  header: {
    textAlign: 'center' as const,
    marginBottom: '20px',
    paddingBottom: '16px',
    borderBottom: '2px solid #1f2937',
  },
  title: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#111827',
    margin: '0 0 4px 0',
    lineHeight: '32px',
    display: 'block',
  },
  subtitle: {
    fontSize: '12px',
    color: '#9ca3af',
    margin: 0,
    lineHeight: '18px',
    display: 'block',
  },
  infoBox: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '20px',
    padding: '14px',
    backgroundColor: '#f9fafb',
    borderRadius: '6px',
  },
  infoRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '8px',
  },
  infoLabel: {
    width: '60px',
    fontSize: '11px',
    color: '#6b7280',
    lineHeight: '18px',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  infoValue: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#111827',
    lineHeight: '20px',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  infoValueSmall: {
    fontSize: '12px',
    fontWeight: '500',
    color: '#111827',
    lineHeight: '18px',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  section: {
    marginBottom: '18px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: '10px',
    paddingBottom: '6px',
    borderBottom: '1px solid #e5e7eb',
    lineHeight: '22px',
  },
  colorBar: (color: string) => ({
    width: '4px',
    height: '16px',
    backgroundColor: color,
    borderRadius: '2px',
    flexShrink: 0,
  }),
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '12px',
  },
  th: {
    padding: '8px 6px',
    textAlign: 'center' as const,
    verticalAlign: 'middle' as const,
    fontWeight: '600',
    color: '#374151',
    backgroundColor: '#f3f4f6',
    border: '1px solid #e5e7eb',
    lineHeight: '20px',
    fontSize: '12px',
    boxSizing: 'border-box' as const,
  },
  td: {
    padding: '8px 6px',
    textAlign: 'center' as const,
    verticalAlign: 'middle' as const,
    border: '1px solid #e5e7eb',
    lineHeight: '20px',
    fontSize: '12px',
    boxSizing: 'border-box' as const,
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '8px',
  },
  card: {
    padding: '10px',
    backgroundColor: '#fff7ed',
    borderRadius: '6px',
    border: '1px solid #fed7aa',
  },
  cardLabel: {
    fontSize: '11px',
    color: '#6b7280',
    marginBottom: '4px',
    lineHeight: '16px',
    display: 'block',
  },
  cardValue: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#111827',
    lineHeight: '22px',
    display: 'block',
  },
  cardUnit: {
    fontSize: '11px',
    fontWeight: 'normal',
    color: '#6b7280',
    marginLeft: '2px',
  },
  universityBox: {
    display: 'flex',
    gap: '12px',
  },
  universityCard: (isPrimary: boolean) => ({
    flex: 1,
    padding: '12px',
    backgroundColor: isPrimary ? '#faf5ff' : '#f9fafb',
    borderRadius: '6px',
    border: `1px solid ${isPrimary ? '#e9d5ff' : '#e5e7eb'}`,
  }),
  universityLabel: (isPrimary: boolean) => ({
    fontSize: '11px',
    fontWeight: '500',
    color: isPrimary ? '#9333ea' : '#6b7280',
    marginBottom: '4px',
    lineHeight: '16px',
    display: 'block',
  }),
  universityName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#111827',
    lineHeight: '22px',
    display: 'block',
  },
  memoBox: (color: string) => ({
    marginTop: '10px',
    padding: '10px',
    backgroundColor: color,
    borderRadius: '6px',
    fontSize: '12px',
    color: '#374151',
    lineHeight: '20px',
  }),
  contentBox: {
    padding: '14px',
    backgroundColor: '#f0fdf4',
    borderRadius: '6px',
    border: '1px solid #bbf7d0',
  },
  contentText: {
    fontSize: '12px',
    color: '#374151',
    whiteSpace: 'pre-wrap' as const,
    lineHeight: '20px',
    margin: 0,
  },
  footer: {
    marginTop: '20px',
    paddingTop: '10px',
    borderTop: '1px solid #e5e7eb',
    textAlign: 'center' as const,
  },
  footerText: {
    fontSize: '11px',
    color: '#9ca3af',
    margin: 0,
    lineHeight: '16px',
    display: 'block',
  },
};
